name: Laravel CI/CD

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up PHP
      uses: shivammathur/setup-php@v3
      with:
        php-version: '8.2'

    - name: Install dependencies
      run: composer install --no-progress --no-suggest

    - name: Copy environment file
      run: cp .env.example .env

    - name: Generate application key
      run: php artisan key:generate

    - name: Run migrations
      run: php artisan migrate

    - name: Run tests
      run: php artisan test

  deploy:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy via SSH
      env:
        HOST: ${{ secrets.SSH_HOST }}
        USERNAME: ${{ secrets.SSH_USERNAME }}
        KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SCRIPT: |
          cd /var/www/paysoko
          git pull origin main
          composer install --no-dev --optimize-autoloader
          php artisan migrate --force
          php artisan config:cache
          php artisan route:cache
      run: |
        echo "${{ env.KEY }}" > private.key
        chmod 600 private.key
        ssh -i private.key -o StrictHostKeyChecking=no ${{ env.USERNAME }}@${{ env.HOST }} "${{ env.SCRIPT }}"
